### ISSUE TITLE
Raster to polygon (st_as_sf) does not work for subset of raster that does not start at index 1 (in x and y)

### ISSUE THREAD

**Issue by bevingtona** [r-spatial/stars#310]
I would like to convert a subset of a raster to polygon. 

In the example below, I successfully convert the entire raster to polygon, and a subset of `x` and `y` from `1:50`, but for some reason when the subset of `x` and `y` does not start at `1`, `st_as_sf` does not seem to work (see last line of the reprex code).

Or is this an `sf` issue? 

Thanks! 

``` r
  library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
  library(sf)
  
  # Read raster
  tif <- system.file("tif/olinda_dem_utm25s.tif", package = "stars")
  tif_proxy <- read_stars(tif, proxy = F)
  
  # Boolean raster (greater than 20)
  tif_proxy_gt20 <- tif_proxy>20
  plot(tif_proxy_gt20)
```

![](https://i.imgur.com/AWKFSzB.png)

``` r
  
  # WORKS
  # 1. Convert entire raster to polygon 
  tif_proxy_gt20 %>% sf::st_as_sf(as_points = F, merge = T) %>% plot()
```

![](https://i.imgur.com/X8zB4XG.png)

``` r
  
  # WORKS
  # 2. Subset raster from 1:50 (in x and y) and convert to polygon 
  tif_proxy_gt20[,1:50,1:50] %>%  sf::st_as_sf(as_points = F, merge = T) %>% plot()
```

![](https://i.imgur.com/HHYbWSg.png)

``` r
  
  # DOES NOT WORK
  # 3. Subset raster from 2:50 (in x and y) and convert to polygon 
  tif_proxy_gt20[,2:50,2:50] %>%  sf::st_as_sf(as_points = F, merge = T) %>% plot()
#> Error in gdal_write(x, file = file, driver = driver, geotransform = geotransform): cannot write sub-rasters only
```

<sup>Created on 2020-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Thanks! Should work now.

**Comment by bevingtona** [comment]
Great, thanks @edzer! 
I've updated `stars` from GitHub and the problem persists (on both Windows and Ubuntu). 
Any thoughts? Thanks again! 

``` r
devtools::install_github("r-spatial/stars", force = T)
#> Downloading GitHub repo r-spatial/stars@master
#> 
#>          checking for file 'C:\Users\bevin\AppData\Local\Temp\Rtmp4ubghP\remotes48f46fad9bc\r-spatial-stars-72064b3/DESCRIPTION' ...     checking for file 'C:\Users\bevin\AppData\Local\Temp\Rtmp4ubghP\remotes48f46fad9bc\r-spatial-stars-72064b3/DESCRIPTION' ...   v  checking for file 'C:\Users\bevin\AppData\Local\Temp\Rtmp4ubghP\remotes48f46fad9bc\r-spatial-stars-72064b3/DESCRIPTION'
#>       -  preparing 'stars': (936ms)
#>    checking DESCRIPTION meta-information ...     checking DESCRIPTION meta-information ...   v  checking DESCRIPTION meta-information
#>       -  checking for LF line-endings in source and make files and shell scripts
#>       -  checking for empty or unneeded directories
#>       -  building 'stars_0.4-4.tar.gz'
#>      
#> 
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(sf)
packageVersion("stars")
#> [1] '0.4.4'
packageVersion("sf")
#> [1] '0.9.6'

# Read raster
tif <- system.file("tif/olinda_dem_utm25s.tif", package = "stars")
tif_proxy <- read_stars(tif, proxy = F)

# Boolean raster (greater than 20)
tif_proxy_gt20 <- tif_proxy>20
plot(tif_proxy_gt20)
```

![](https://i.imgur.com/UZjdCgR.png)

``` r

# WORKS
# 1. Convert entire raster to polygon 
# tif_proxy_gt20 %>% sf::st_as_sf(as_points = F, merge = T) %>% plot()

# WORKS
# 2. Subset raster from 1:50 (in x and y) and convert to polygon 
# tif_proxy_gt20[,1:50,1:50] %>%  sf::st_as_sf(as_points = F, merge = T) %>% plot()

# DOES NOT WORK
# 3. Subset raster from 2:50 (in x and y) and convert to polygon 
tif_proxy_gt20[,2:50,2:50] %>%  sf::st_as_sf(as_points = F, merge = T) %>% plot()
#> Error in gdal_write(mask, file = mask_name, driver = driver, geotransform = geotransform): cannot write sub-rasters only
```

<sup>Created on 2020-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bevingtona** [comment]
Sorry, still not working for me, even specified the commit reference:
`devtools::install_github("r-spatial/stars", force = T,  ref = "af10b860909b37ac76e267c39112d48fdf7f80f6")`

I found a work around for the time being (subset and save geotif, read with `raster` package, convert to `stars`, then polygonize)... 

``` r
t <- tempfile(fileext = ".tif")
tif_proxy_gt20[,2:50,2:50] %>%  write_stars(t)
raster::raster(t) %>% st_as_stars() %>% st_as_sf(as_points = F, merge = T) %>% plot()
```

**Comment by edzer** [comment]
No need for the commit ref, as this was committed to master. Very odd. Can you give your `sessionInfo()` after loading stars?

**Comment by bevingtona** [comment]
It works today! See below, with sessionInfo. 
Thanks @edzer!

``` r
devtools::install_github("r-spatial/stars", force = T)
#> Downloading GitHub repo r-spatial/stars@master
#> 
#>          checking for file 'C:\Users\bevin\AppData\Local\Temp\Rtmpag8PTB\remotes7a0cee1caf\r-spatial-stars-f3d506e/DESCRIPTION' ...     checking for file 'C:\Users\bevin\AppData\Local\Temp\Rtmpag8PTB\remotes7a0cee1caf\r-spatial-stars-f3d506e/DESCRIPTION' ...   v  checking for file 'C:\Users\bevin\AppData\Local\Temp\Rtmpag8PTB\remotes7a0cee1caf\r-spatial-stars-f3d506e/DESCRIPTION'
#>       -  preparing 'stars': (1s)
#>    checking DESCRIPTION meta-information ...     checking DESCRIPTION meta-information ...   v  checking DESCRIPTION meta-information
#>       -  checking for LF line-endings in source and make files and shell scripts
#>       -  checking for empty or unneeded directories
#>       -  building 'stars_0.4-4.tar.gz'
#>      
#> 
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(sf)
packageVersion("stars")
#> [1] '0.4.4'
packageVersion("sf")
#> [1] '0.9.6'

# Read raster
tif <- system.file("tif/olinda_dem_utm25s.tif", package = "stars")
tif_proxy <- read_stars(tif, proxy = F)

# Boolean raster (greater than 20)
tif_proxy_gt20 <- tif_proxy>20
# plot(tif_proxy_gt20)

# WORKS
# 1. Convert entire raster to polygon 
# tif_proxy_gt20 %>% sf::st_as_sf(as_points = F, merge = T) %>% plot()

# WORKS
# 2. Subset raster from 1:50 (in x and y) and convert to polygon 
# tif_proxy_gt20[,1:50,1:50] %>%  sf::st_as_sf(as_points = F, merge = T) %>% plot()

# DOES NOT WORK
# 3. Subset raster from 2:50 (in x and y) and convert to polygon 
tif_proxy_gt20[,20:50,20:50] %>%  sf::st_as_sf(as_points = F, merge = T) %>% plot()
```

![](https://i.imgur.com/GQ1yRPT.png)

``` r

sessionInfo()
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18362)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
#> [3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=English_Canada.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] stars_0.4-4 sf_0.9-6    abind_1.4-5
#> 
#> loaded via a namespace (and not attached):
#>  [1] tidyselect_1.1.0   xfun_0.13          remotes_2.1.1      purrr_0.3.4       
#>  [5] vctrs_0.3.2        generics_0.0.2     testthat_2.3.2     usethis_1.6.0     
#>  [9] htmltools_0.4.0    yaml_2.2.1         rlang_0.4.7        pkgbuild_1.0.7    
#> [13] e1071_1.7-3        pillar_1.4.3       glue_1.4.0         withr_2.2.0       
#> [17] DBI_1.1.0          sessioninfo_1.1.1  lifecycle_0.2.0    stringr_1.4.0     
#> [21] devtools_2.3.0     memoise_1.1.0      evaluate_0.14      knitr_1.28        
#> [25] callr_3.4.3        ps_1.3.2           parallel_3.6.1     curl_4.3          
#> [29] class_7.3-16       fansi_0.4.1        highr_0.8          Rcpp_1.0.5        
#> [33] KernSmooth_2.23-16 backports_1.1.6    classInt_0.4-3     lwgeom_0.2-5      
#> [37] desc_1.2.0         pkgload_1.0.2      fs_1.4.1           digest_0.6.25     
#> [41] stringi_1.4.6      processx_3.4.2     dplyr_1.0.1        rprojroot_1.3-2   
#> [45] grid_3.6.1         cli_2.0.2          tools_3.6.1        magrittr_1.5      
#> [49] tibble_3.0.1       crayon_1.3.4       pkgconfig_2.0.3    ellipsis_0.3.0    
#> [53] prettyunits_1.1.1  assertthat_0.2.1   rmarkdown_2.1      R6_2.4.1          
#> [57] units_0.6-7        compiler_3.6.1
```

<sup>Created on 2020-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
